/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tzfxbgxnjkthxwvoeyse";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZnhiZ3huamt0aHh3dm9leXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjMyNzksImV4cCI6MjA3NzkzOTI3OX0.ppdC65PkGV4rizRXujNYqU3BDwnAnRCzTvX7LFlmyUk";
